updates:
  - directory: /
    groups:
      github-actions:
        patterns:
          - '*'
    package-ecosystem: github-actions
    schedule:
      interval: daily
      time: '05:00'
  - directory: /
    groups:
      npm-dependencies:
        patterns:
          - '*'
    package-ecosystem: npm
    schedule:
      interval: daily
      time: '05:00'
version: 2
