name: Publish app on Homey
on:
  workflow_dispatch:

jobs:
  main:
    name: Publish app on Homey
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Publish
        uses: athombv/github-action-homey-app-publish@v1
        id: publish
        with:
          personal_access_token: ${{ secrets.HOMEY_PAT }}
      - name: URL
        run: echo "Manage your app at ${{ steps.publish.outputs.url }}." >> $GITHUB_STEP_SUMMARY
