name: Update app version
on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Version
        required: true
        default: patch
        options:
          - major
          - minor
          - patch
      changelog:
        type: string
        description: Changelog
        required: true

jobs:
  update-version:
    name: Update app version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update app version
        uses: athombv/github-action-homey-app-version@master
        id: update_app_version
        with:
          version: ${{ inputs.version }}
          changelog: ${{ inputs.changelog }}
      - name: Commit & push changes
        run: |
          VERSION=${{ steps.update_app_version.outputs.version }}
          npm version $VERSION --no-git-tag-version --allow-same-version
          git config --local user.email "sysadmin+githubactions@athom.com"
          git config --local user.name "Homey Github Actions Bot"
          git add -A
          git commit -m "Update app version to v$VERSION"
          git tag "v$VERSION"
          git push origin HEAD --tags
