name: Validate app
on:
  push:
    branches: main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  main:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: Lint & format code
        run: npm ci
      - name: Build code & validate app
        uses: athombv/github-action-homey-app-validate@master
        with:
          level: publish
      - name: Commit & push
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          if ! git diff --cached --exit-code; then
            git commit -m "Code maintenance: lint, format and build code"
            if [[ ${{ github.ref }} == "refs/heads/main" ]]; then
              echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
              BRANCH_NAME="maintenance-$(date +'%Y%m%d%H%M%S')"
              git checkout -b "$BRANCH_NAME"
              git push origin "$BRANCH_NAME"
              gh pr create --base main --head "$BRANCH_NAME" --title "Maintenance PR" --body "Automatic code maintenance: lint, format and build code."
              gh pr merge --auto --squash --delete-branch ${{ github.event.pull_request.html_url }}
            else
              git pull origin ${{ github.head_ref }} --rebase
              git push origin HEAD:${{ github.head_ref }}
            fi
          fi
